# Generated by Django 3.2.1 on 2021-09-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210905_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='order',
        ),
    ]
