# Generated by Django 3.2.1 on 2021-09-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210906_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='order',
        ),
    ]
