# Generated by Django 3.2.1 on 2021-09-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210907_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AddField(
            model_name='reason',
            name='order',
            field=models.IntegerField(default=0, verbose_name='orden'),
        ),
    ]
